### ISSUE TITLE
Not subscribe to observation on newly created identification

### ISSUE THREAD

**Issue by jtklein** [inaturalist/inaturalistjs#22]
Hej,
is it possible to add a param to the creation of an identification that leads to not being subscribed to the observation? Maybe a better place to add this issue would be the API itself, but I would need the param here as well.

(I have seen the method subscribe which presumably toggles that, but it takes a very long time for my identifications to hit the servers and an unsubscribe with this method after await of the new id would take too long.)

**Comment by jtklein** [comment]
OK, sure, I will try! I don't think there is anything bad in subscribing to an observation, however, I don't need it for all identifications I make. (In my use case I make a lot of ids in a short time, but am only interested in following in maybe half of the ids.) Anyway, for the ids that I don't want to follow I have to make two requests (one for creating and one for unsubscribing). So just to cut the number of requests in half it would be good, if the `.create()` would process a param to not subscribe.

I am assuming that I have to make the create request first (which toggles on the subscription to the observation), then make the unsubscribe request after the first one is finished. Did you mean that I can make the two requests at the same time, so in case the unsubscribe hits first, the create requests toggles it to unsubscribe? Probably not.
There are scenarios (like switching off the app in between) where waiting for the first response will then not be followed by the second, then just one request would also be good.

**Comment by kueda** [comment]
If it's not something you need for all identifications you add then I think I'd prefer that you use the existing subscriptions API endpoint. And yes, it's an additional request but this is kind of an edge case in my opinion.

I was just recommending that you perform the subscription requests asynchronously from future identification requests, but if we're talking about https://github.com/jtklein/inat-identify/blob/master/inat-identify/src/screens/IiIdentifyScreen.js, it looks like you're already doing that.

@pleary, do you have an opinion on this?

**Comment by pleary** [comment]
For observation subscriptions, you're either subscribed or you're not - there is no state that is something like "keep me unsubscribed". And the endpoint http://api.inaturalist.org/v1/docs/#!/Observations/post_subscriptions_observation_id_subscribe just toggles the subscription. So if you make the subscribe call before adding the identification, the subscribe call will subscribe you to the observation, and creating the ID will look to see if you're subscribed, and you will be, so it would just leave you subscribed.

Or let's say you make the subscribe call, the make it again to unsubscribe, and then create the identification - the create ID call will check to see if you're subscribed, which you won't be, and will subscribe you.

Since we don't have a feature to opt out of auto-subscribing to observations you ID, I think your code as you have it is the closest you can get right now. You will need to wait for identification create request to be complete before unsubscribing, otherwise the ID create request will subscribe you. And the unsubscribe request can be made asynchronously w/o needing to wait for the response. But as you say, if the user closes the app after making the ID and before it responds and the unsubscribe call is made, they will remain subscribed.
