### ISSUE TITLE
Add a barrier for too many requests

### ISSUE THREAD

**Issue by jtklein** [inaturalist/inaturalistjs#37]
I have encountered a 429 response from the server in my application (too many requests). Probably, I came over one of the limits specified in the api documentation: "Please note that we throttle API usage to a max of 100 requests per minute, though we ask that you try to keep it to 60 requests per minute or lower, and to keep under 10,000 requests per day." I can add checks to not get over this limit in my application.

But I think it might be beneficial if the library itself checks for the limits, and does not make too many requests when used.

**Comment by kueda** [comment]
Just so I understand what you're asking for, you want inatjs to catch 429 errors... and then what? Redo the request in 10 seconds? Exponential backoff? Or do you what inatjs to actually monitor the request and throttle itself *before* it starts getting 429 errors?

I guess I don't have a strong opinion on this, but my weak opinion is that the client software is the party making the requests, so it should be the client's responsibility to moderate the rate of those requests, and it will be confusing to the client developer if some requests start taking a very long time because the library is waiting to throttling itself. The 429 error you got immediately told you, the developer, what went wrong, and allowed you to start working on a solution. A very slow request could have meant network issues, a problem with the iNat servers, something weird going on with your host hardware or OS... much harder to debug.

But, like I said, I'm not opposed if others like this. @albullington? @pleary?

**Comment by pleary** [comment]
I'd need to see this specced out to give a complete answer. My initial inclination is this isn't the responsibility of the library, and anyone implementing this needs to handle 429 errors themselves in their own code.

As @kueda asked - what would inaturalistjs do in the case the requests needed to be throttled? Right now it'll make the request and return an error, and it's up to the client to handle the error. How would you implement such that a client doesn't have to handle an error? If if the client does need to handle an error, would it be significantly different than handling an HTTP 429 response?

Among the reasons I don't think this should go into inaturalistjs are:
- This library currently keeps almost no state. You can set some configuration and that's it - a couple of strings. I wouldn't want it to use up resources keeping track of requests to the various endpoints
- It's impossible for this library to know about requests made outside the library. If you have multiple processes are using inatjs behind the same IP, they wouldn't be aware of each other and thus it would still need to handle 429 errors if one instance made 9999 requests and the second made just 2. So if the library needs to handle 429 errors anyway, implementing something else means that client implementations would need multiple ways to handle throttling errors
- We reserve the right to change throttling rules at any time. I'd rather not have to keep the throttling rules in this repo in sync with the main throttling rules if we do decide to update them. And if we ever wanted more conservative rules, and someone using this code didn't update, their code might think it could make more requests than it could, and if it went beyond the new limit, the client would again hit a 429 error

**Comment by jtklein** [comment]
Thank you, all very good points.
I was not arguing for an internal handling of 429 errors. That belongs on the client side, I agree.

I was thinking more of a counter inside the library to not get over the limit of requests. If the limit is reached the library would not make any requests to the servers until it is free again. Such counter would only prevent your servers from excess requests that would not lead to anything anyway. I can understand that you don't want to keep any state, if you don't have already.
